import Head from "next/head";
import Image from "next/image";
import { Disclosure } from "@headlessui/react";
import { MagnifyingGlassIcon } from "@heroicons/react/20/solid";
import { Bars3Icon, XMarkIcon } from "@heroicons/react/24/outline";
import clsx from "clsx";

const navigation = [
  { name: "Acerca", href: "#", current: false },
  { name: "Explorar", href: "#", current: false },
  { name: "Directorio", href: "#", current: false },
  { name: "Entrar", href: "#", current: true },
];

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-primary h-screen  ">
        <Disclosure as="header" className=" bg-white">
          {({ open }) => (
            <>
              <div
                className={clsx(
                  " transition-colors mx-auto px-2 sm:px-4 lg:divide-y lg:divide-gray-700 lg:px-8 ",
                  {
                    "bg-white": open,
                    "bg-primary": open === false,
                  }
                )}
              >
                <div className="relative flex h-16 justify-between">
                  <div className="relative z-10 flex px-2 lg:px-0">
                    <div className="flex flex-shrink-0 items-center">
                      <button
                        className={clsx(
                          "inline-flex lg:hidden items-center justify-center rounded-full p-2  focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white",
                          {
                            "text-black hover:bg-slate-200/50 focus:ring-primary":
                              open,
                            "text-black hover:bg-slate-200/50 focus:ring-white":
                              open === false,
                          }
                        )}
                      >
                        <span className="sr-only">Open menu</span>
                        <MagnifyingGlassIcon
                          className="h-5 w-5 text-black"
                          aria-hidden="true"
                        />
                      </button>

                      <img
                        className="hidden lg:block h-8 w-auto "
                        src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500"
                        alt="Your Company"
                      />
                    </div>
                  </div>
                  <div className="relative lg:hidden z-0 flex flex-1 items-center justify-center px-2 lg:absolute lg:inset-0">
                    <img
                      className=" h-8 w-auto "
                      src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500"
                      alt="Your Company"
                    />
                  </div>

                  <div className="relative hidden z-0 lg:flex flex-1 items-center justify-center px-2 lg:absolute lg:inset-0">
                    <div className="w-full sm:max-w-xs">
                      <label htmlFor="Buscar" className="sr-only">
                        Buscar
                      </label>
                      <div className="relative">
                        <div className="pointer-events-none absolute inset-y-0 right-2 flex items-center pr-3">
                          <MagnifyingGlassIcon
                            className="h-5 w-5 text-black"
                            aria-hidden="true"
                          />
                        </div>
                        <input
                          id="Buscar"
                          name="Buscar"
                          className="block w-full rounded-full border placeholder:text-slate-600 border-slate-600  py-2 pr-10 pl-3 text-sm outline-none focus:border-slate-600 focus:ring-0 bg-transparent"
                          placeholder="Buscar"
                          type="text"
                        />
                      </div>
                    </div>
                  </div>
                  <div className="relative z-10 flex items-center lg:hidden">
                    {/* Mobile menu button */}
                    <Disclosure.Button
                      className={clsx(
                        "inline-flex items-center justify-center rounded-full p-2  focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white",
                        {
                          "text-black hover:bg-slate-200/50 focus:ring-primary":
                            open,
                          "text-black hover:bg-slate-200/50 focus:ring-white":
                            open === false,
                        }
                      )}
                    >
                      <span className="sr-only">Open menu</span>
                      {open ? (
                        <XMarkIcon
                          className="block h-6 w-6"
                          aria-hidden="true"
                        />
                      ) : (
                        <Bars3Icon
                          className="block h-6 w-6"
                          aria-hidden="true"
                        />
                      )}
                    </Disclosure.Button>
                  </div>
                  <div className="hidden lg:relative lg:z-10 lg:ml-4 lg:flex lg:gap-3 lg:items-center">
                    <button
                      type="button"
                      className="flex-shrink-0 rounded-full text-black py-2 px-4 hover:bg-slate-100/50  focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800 "
                    >
                      Explorar
                    </button>
                    <button
                      type="button"
                      className="flex-shrink-0 rounded-full text-black py-2 px-4 hover:bg-slate-100/50 focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800 "
                    >
                      Registro
                    </button>

                    <button
                      type="button"
                      className="flex-shrink-0 rounded-full bg-black py-2 px-4 text-white hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800 "
                    >
                      Registro
                    </button>
                  </div>
                </div>
              </div>

              <Disclosure.Panel
                as="nav"
                className="lg:hidden"
                aria-label="Global"
              >
                <div className="space-y-1 px-2 pt-2 pb-3">
                  {navigation.map((item) => (
                    <Disclosure.Button
                      key={item.name}
                      as="a"
                      href={item.href}
                      className={clsx(
                        item.current
                          ? "text-gray-300"
                          : "text-gray-700 hover:bg-primary/50 ",
                        "block rounded-md py-2 px-3 text-base font-medium"
                      )}
                      aria-current={item.current ? "page" : undefined}
                    >
                      {item.name}
                    </Disclosure.Button>
                  ))}
                </div>
              </Disclosure.Panel>
            </>
          )}
        </Disclosure>
        <div className="flex items-center justify-center flex-col mt-20 md:mt-10 lg:mt-20 container mx-auto">
          <div className="  text-6xl  md:text-7xl lg:text-8xl  md:px-40 break-words px-8">
            Casco 🌠 San @ Pedro -- CASCO @ DE 🏞 TODOS 🐩
          </div>
        </div>
      </div>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
